name: Nx Mongo Migrate

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: yarn install
      # - run: npx nx affected --target=publish
      - run: npx nx run mongo-migrate:publish
        env:
          NPM_TOKEN: ${{secrets.PACKAGES_PAT}}
